################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.o Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.su Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../Drivers/CMSIS/DSP/Source/StatisticsFunctions/%.c Drivers/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L475xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../X-CUBE-AI -I../X-CUBE-AI/Target -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/Drivers/CMSIS/Core/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/Drivers/CMSIS/DSP/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/Drivers/CMSIS/DSP/PrivateInclude" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/Drivers/CMSIS/DSP/Include/dsp" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/Drivers/CMSIS/NN/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/tensorflow" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/tensorflow/lite/micro" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/tensorflow/lite/schema" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/tensorflow/lite/kernels" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/tensorflow/lite/micro/memory_planner" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/third_party/flatbuffers/include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/third_party/gemmlowp" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/third_party/kissfft" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/UrbanSound8K_QAT/tensorflow_lite/third_party/ruy" -I../X-CUBE-AI/App -I../Middlewares/ST/AI/Inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d
	-$(RM) ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

