################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../lite/micro/kernels/activations.cc \
../lite/micro/kernels/activations_common.cc \
../lite/micro/kernels/add_common.cc \
../lite/micro/kernels/add_n.cc \
../lite/micro/kernels/arg_min_max.cc \
../lite/micro/kernels/assign_variable.cc \
../lite/micro/kernels/batch_to_space_nd.cc \
../lite/micro/kernels/broadcast_args.cc \
../lite/micro/kernels/broadcast_to.cc \
../lite/micro/kernels/call_once.cc \
../lite/micro/kernels/cast.cc \
../lite/micro/kernels/ceil.cc \
../lite/micro/kernels/circular_buffer.cc \
../lite/micro/kernels/circular_buffer_common.cc \
../lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cc \
../lite/micro/kernels/comparisons.cc \
../lite/micro/kernels/concatenation.cc \
../lite/micro/kernels/conv_common.cc \
../lite/micro/kernels/cumsum.cc \
../lite/micro/kernels/depth_to_space.cc \
../lite/micro/kernels/depthwise_conv_common.cc \
../lite/micro/kernels/dequantize.cc \
../lite/micro/kernels/dequantize_common.cc \
../lite/micro/kernels/detection_postprocess.cc \
../lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc \
../lite/micro/kernels/div.cc \
../lite/micro/kernels/elementwise.cc \
../lite/micro/kernels/elu.cc \
../lite/micro/kernels/ethosu.cc \
../lite/micro/kernels/exp.cc \
../lite/micro/kernels/expand_dims.cc \
../lite/micro/kernels/fill.cc \
../lite/micro/kernels/floor.cc \
../lite/micro/kernels/floor_div.cc \
../lite/micro/kernels/floor_mod.cc \
../lite/micro/kernels/fully_connected_common.cc \
../lite/micro/kernels/gather.cc \
../lite/micro/kernels/gather_nd.cc \
../lite/micro/kernels/hard_swish.cc \
../lite/micro/kernels/hard_swish_common.cc \
../lite/micro/kernels/if.cc \
../lite/micro/kernels/kernel_runner.cc \
../lite/micro/kernels/kernel_util.cc \
../lite/micro/kernels/l2_pool_2d.cc \
../lite/micro/kernels/l2norm.cc \
../lite/micro/kernels/leaky_relu.cc \
../lite/micro/kernels/leaky_relu_common.cc \
../lite/micro/kernels/log_softmax.cc \
../lite/micro/kernels/logical.cc \
../lite/micro/kernels/logical_common.cc \
../lite/micro/kernels/logistic.cc \
../lite/micro/kernels/logistic_common.cc \
../lite/micro/kernels/lstm_eval.cc \
../lite/micro/kernels/maximum_minimum.cc \
../lite/micro/kernels/micro_tensor_utils.cc \
../lite/micro/kernels/mirror_pad.cc \
../lite/micro/kernels/mul_common.cc \
../lite/micro/kernels/neg.cc \
../lite/micro/kernels/pack.cc \
../lite/micro/kernels/pad.cc \
../lite/micro/kernels/pooling_common.cc \
../lite/micro/kernels/prelu.cc \
../lite/micro/kernels/prelu_common.cc \
../lite/micro/kernels/quantize.cc \
../lite/micro/kernels/quantize_common.cc \
../lite/micro/kernels/read_variable.cc \
../lite/micro/kernels/reduce.cc \
../lite/micro/kernels/reduce_common.cc \
../lite/micro/kernels/reshape.cc \
../lite/micro/kernels/resize_bilinear.cc \
../lite/micro/kernels/resize_nearest_neighbor.cc \
../lite/micro/kernels/round.cc \
../lite/micro/kernels/shape.cc \
../lite/micro/kernels/slice.cc \
../lite/micro/kernels/softmax_common.cc \
../lite/micro/kernels/space_to_batch_nd.cc \
../lite/micro/kernels/space_to_depth.cc \
../lite/micro/kernels/split.cc \
../lite/micro/kernels/split_v.cc \
../lite/micro/kernels/squared_difference.cc \
../lite/micro/kernels/squeeze.cc \
../lite/micro/kernels/strided_slice.cc \
../lite/micro/kernels/sub.cc \
../lite/micro/kernels/sub_common.cc \
../lite/micro/kernels/svdf_common.cc \
../lite/micro/kernels/tanh.cc \
../lite/micro/kernels/transpose.cc \
../lite/micro/kernels/transpose_conv.cc \
../lite/micro/kernels/unidirectional_sequence_lstm.cc \
../lite/micro/kernels/unpack.cc \
../lite/micro/kernels/var_handle.cc \
../lite/micro/kernels/while.cc \
../lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./lite/micro/kernels/activations.d \
./lite/micro/kernels/activations_common.d \
./lite/micro/kernels/add_common.d \
./lite/micro/kernels/add_n.d \
./lite/micro/kernels/arg_min_max.d \
./lite/micro/kernels/assign_variable.d \
./lite/micro/kernels/batch_to_space_nd.d \
./lite/micro/kernels/broadcast_args.d \
./lite/micro/kernels/broadcast_to.d \
./lite/micro/kernels/call_once.d \
./lite/micro/kernels/cast.d \
./lite/micro/kernels/ceil.d \
./lite/micro/kernels/circular_buffer.d \
./lite/micro/kernels/circular_buffer_common.d \
./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d \
./lite/micro/kernels/comparisons.d \
./lite/micro/kernels/concatenation.d \
./lite/micro/kernels/conv_common.d \
./lite/micro/kernels/cumsum.d \
./lite/micro/kernels/depth_to_space.d \
./lite/micro/kernels/depthwise_conv_common.d \
./lite/micro/kernels/dequantize.d \
./lite/micro/kernels/dequantize_common.d \
./lite/micro/kernels/detection_postprocess.d \
./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d \
./lite/micro/kernels/div.d \
./lite/micro/kernels/elementwise.d \
./lite/micro/kernels/elu.d \
./lite/micro/kernels/ethosu.d \
./lite/micro/kernels/exp.d \
./lite/micro/kernels/expand_dims.d \
./lite/micro/kernels/fill.d \
./lite/micro/kernels/floor.d \
./lite/micro/kernels/floor_div.d \
./lite/micro/kernels/floor_mod.d \
./lite/micro/kernels/fully_connected_common.d \
./lite/micro/kernels/gather.d \
./lite/micro/kernels/gather_nd.d \
./lite/micro/kernels/hard_swish.d \
./lite/micro/kernels/hard_swish_common.d \
./lite/micro/kernels/if.d \
./lite/micro/kernels/kernel_runner.d \
./lite/micro/kernels/kernel_util.d \
./lite/micro/kernels/l2_pool_2d.d \
./lite/micro/kernels/l2norm.d \
./lite/micro/kernels/leaky_relu.d \
./lite/micro/kernels/leaky_relu_common.d \
./lite/micro/kernels/log_softmax.d \
./lite/micro/kernels/logical.d \
./lite/micro/kernels/logical_common.d \
./lite/micro/kernels/logistic.d \
./lite/micro/kernels/logistic_common.d \
./lite/micro/kernels/lstm_eval.d \
./lite/micro/kernels/maximum_minimum.d \
./lite/micro/kernels/micro_tensor_utils.d \
./lite/micro/kernels/mirror_pad.d \
./lite/micro/kernels/mul_common.d \
./lite/micro/kernels/neg.d \
./lite/micro/kernels/pack.d \
./lite/micro/kernels/pad.d \
./lite/micro/kernels/pooling_common.d \
./lite/micro/kernels/prelu.d \
./lite/micro/kernels/prelu_common.d \
./lite/micro/kernels/quantize.d \
./lite/micro/kernels/quantize_common.d \
./lite/micro/kernels/read_variable.d \
./lite/micro/kernels/reduce.d \
./lite/micro/kernels/reduce_common.d \
./lite/micro/kernels/reshape.d \
./lite/micro/kernels/resize_bilinear.d \
./lite/micro/kernels/resize_nearest_neighbor.d \
./lite/micro/kernels/round.d \
./lite/micro/kernels/shape.d \
./lite/micro/kernels/slice.d \
./lite/micro/kernels/softmax_common.d \
./lite/micro/kernels/space_to_batch_nd.d \
./lite/micro/kernels/space_to_depth.d \
./lite/micro/kernels/split.d \
./lite/micro/kernels/split_v.d \
./lite/micro/kernels/squared_difference.d \
./lite/micro/kernels/squeeze.d \
./lite/micro/kernels/strided_slice.d \
./lite/micro/kernels/sub.d \
./lite/micro/kernels/sub_common.d \
./lite/micro/kernels/svdf_common.d \
./lite/micro/kernels/tanh.d \
./lite/micro/kernels/transpose.d \
./lite/micro/kernels/transpose_conv.d \
./lite/micro/kernels/unidirectional_sequence_lstm.d \
./lite/micro/kernels/unpack.d \
./lite/micro/kernels/var_handle.d \
./lite/micro/kernels/while.d \
./lite/micro/kernels/zeros_like.d 

OBJS += \
./lite/micro/kernels/activations.o \
./lite/micro/kernels/activations_common.o \
./lite/micro/kernels/add_common.o \
./lite/micro/kernels/add_n.o \
./lite/micro/kernels/arg_min_max.o \
./lite/micro/kernels/assign_variable.o \
./lite/micro/kernels/batch_to_space_nd.o \
./lite/micro/kernels/broadcast_args.o \
./lite/micro/kernels/broadcast_to.o \
./lite/micro/kernels/call_once.o \
./lite/micro/kernels/cast.o \
./lite/micro/kernels/ceil.o \
./lite/micro/kernels/circular_buffer.o \
./lite/micro/kernels/circular_buffer_common.o \
./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o \
./lite/micro/kernels/comparisons.o \
./lite/micro/kernels/concatenation.o \
./lite/micro/kernels/conv_common.o \
./lite/micro/kernels/cumsum.o \
./lite/micro/kernels/depth_to_space.o \
./lite/micro/kernels/depthwise_conv_common.o \
./lite/micro/kernels/dequantize.o \
./lite/micro/kernels/dequantize_common.o \
./lite/micro/kernels/detection_postprocess.o \
./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o \
./lite/micro/kernels/div.o \
./lite/micro/kernels/elementwise.o \
./lite/micro/kernels/elu.o \
./lite/micro/kernels/ethosu.o \
./lite/micro/kernels/exp.o \
./lite/micro/kernels/expand_dims.o \
./lite/micro/kernels/fill.o \
./lite/micro/kernels/floor.o \
./lite/micro/kernels/floor_div.o \
./lite/micro/kernels/floor_mod.o \
./lite/micro/kernels/fully_connected_common.o \
./lite/micro/kernels/gather.o \
./lite/micro/kernels/gather_nd.o \
./lite/micro/kernels/hard_swish.o \
./lite/micro/kernels/hard_swish_common.o \
./lite/micro/kernels/if.o \
./lite/micro/kernels/kernel_runner.o \
./lite/micro/kernels/kernel_util.o \
./lite/micro/kernels/l2_pool_2d.o \
./lite/micro/kernels/l2norm.o \
./lite/micro/kernels/leaky_relu.o \
./lite/micro/kernels/leaky_relu_common.o \
./lite/micro/kernels/log_softmax.o \
./lite/micro/kernels/logical.o \
./lite/micro/kernels/logical_common.o \
./lite/micro/kernels/logistic.o \
./lite/micro/kernels/logistic_common.o \
./lite/micro/kernels/lstm_eval.o \
./lite/micro/kernels/maximum_minimum.o \
./lite/micro/kernels/micro_tensor_utils.o \
./lite/micro/kernels/mirror_pad.o \
./lite/micro/kernels/mul_common.o \
./lite/micro/kernels/neg.o \
./lite/micro/kernels/pack.o \
./lite/micro/kernels/pad.o \
./lite/micro/kernels/pooling_common.o \
./lite/micro/kernels/prelu.o \
./lite/micro/kernels/prelu_common.o \
./lite/micro/kernels/quantize.o \
./lite/micro/kernels/quantize_common.o \
./lite/micro/kernels/read_variable.o \
./lite/micro/kernels/reduce.o \
./lite/micro/kernels/reduce_common.o \
./lite/micro/kernels/reshape.o \
./lite/micro/kernels/resize_bilinear.o \
./lite/micro/kernels/resize_nearest_neighbor.o \
./lite/micro/kernels/round.o \
./lite/micro/kernels/shape.o \
./lite/micro/kernels/slice.o \
./lite/micro/kernels/softmax_common.o \
./lite/micro/kernels/space_to_batch_nd.o \
./lite/micro/kernels/space_to_depth.o \
./lite/micro/kernels/split.o \
./lite/micro/kernels/split_v.o \
./lite/micro/kernels/squared_difference.o \
./lite/micro/kernels/squeeze.o \
./lite/micro/kernels/strided_slice.o \
./lite/micro/kernels/sub.o \
./lite/micro/kernels/sub_common.o \
./lite/micro/kernels/svdf_common.o \
./lite/micro/kernels/tanh.o \
./lite/micro/kernels/transpose.o \
./lite/micro/kernels/transpose_conv.o \
./lite/micro/kernels/unidirectional_sequence_lstm.o \
./lite/micro/kernels/unpack.o \
./lite/micro/kernels/var_handle.o \
./lite/micro/kernels/while.o \
./lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
lite/micro/kernels/%.o lite/micro/kernels/%.su lite/micro/kernels/%.cyclo: ../lite/micro/kernels/%.cc lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L475xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../X-CUBE-AI -I../X-CUBE-AI/Target -I../X-CUBE-AI/App -I../Middlewares/ST/AI/Inc -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/Drivers/CMSIS/Core/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/Drivers/CMSIS/DSP/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/Drivers/CMSIS/DSP/PrivateInclude" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/Drivers/CMSIS/DSP/Include/dsp" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/Drivers/CMSIS/NN/Include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/tensorflow" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/tensorflow/lite/micro" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/third_party/flatbuffers/include" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/third_party/gemmlowp" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/third_party/kissfft" -I"/Users/jeremygerster/STM32CubeIDE/workspace_1.17.0/zuart_conn/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-lite-2f-micro-2f-kernels

clean-lite-2f-micro-2f-kernels:
	-$(RM) ./lite/micro/kernels/activations.cyclo ./lite/micro/kernels/activations.d ./lite/micro/kernels/activations.o ./lite/micro/kernels/activations.su ./lite/micro/kernels/activations_common.cyclo ./lite/micro/kernels/activations_common.d ./lite/micro/kernels/activations_common.o ./lite/micro/kernels/activations_common.su ./lite/micro/kernels/add_common.cyclo ./lite/micro/kernels/add_common.d ./lite/micro/kernels/add_common.o ./lite/micro/kernels/add_common.su ./lite/micro/kernels/add_n.cyclo ./lite/micro/kernels/add_n.d ./lite/micro/kernels/add_n.o ./lite/micro/kernels/add_n.su ./lite/micro/kernels/arg_min_max.cyclo ./lite/micro/kernels/arg_min_max.d ./lite/micro/kernels/arg_min_max.o ./lite/micro/kernels/arg_min_max.su ./lite/micro/kernels/assign_variable.cyclo ./lite/micro/kernels/assign_variable.d ./lite/micro/kernels/assign_variable.o ./lite/micro/kernels/assign_variable.su ./lite/micro/kernels/batch_to_space_nd.cyclo ./lite/micro/kernels/batch_to_space_nd.d ./lite/micro/kernels/batch_to_space_nd.o ./lite/micro/kernels/batch_to_space_nd.su ./lite/micro/kernels/broadcast_args.cyclo ./lite/micro/kernels/broadcast_args.d ./lite/micro/kernels/broadcast_args.o ./lite/micro/kernels/broadcast_args.su ./lite/micro/kernels/broadcast_to.cyclo ./lite/micro/kernels/broadcast_to.d ./lite/micro/kernels/broadcast_to.o ./lite/micro/kernels/broadcast_to.su ./lite/micro/kernels/call_once.cyclo ./lite/micro/kernels/call_once.d ./lite/micro/kernels/call_once.o ./lite/micro/kernels/call_once.su ./lite/micro/kernels/cast.cyclo ./lite/micro/kernels/cast.d ./lite/micro/kernels/cast.o ./lite/micro/kernels/cast.su ./lite/micro/kernels/ceil.cyclo ./lite/micro/kernels/ceil.d ./lite/micro/kernels/ceil.o ./lite/micro/kernels/ceil.su ./lite/micro/kernels/circular_buffer.cyclo ./lite/micro/kernels/circular_buffer.d ./lite/micro/kernels/circular_buffer.o ./lite/micro/kernels/circular_buffer.su ./lite/micro/kernels/circular_buffer_common.cyclo ./lite/micro/kernels/circular_buffer_common.d ./lite/micro/kernels/circular_buffer_common.o ./lite/micro/kernels/circular_buffer_common.su ./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cyclo ./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d ./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o ./lite/micro/kernels/circular_buffer_flexbuffers_generated_data.su ./lite/micro/kernels/comparisons.cyclo ./lite/micro/kernels/comparisons.d ./lite/micro/kernels/comparisons.o ./lite/micro/kernels/comparisons.su ./lite/micro/kernels/concatenation.cyclo ./lite/micro/kernels/concatenation.d ./lite/micro/kernels/concatenation.o ./lite/micro/kernels/concatenation.su ./lite/micro/kernels/conv_common.cyclo ./lite/micro/kernels/conv_common.d ./lite/micro/kernels/conv_common.o ./lite/micro/kernels/conv_common.su ./lite/micro/kernels/cumsum.cyclo ./lite/micro/kernels/cumsum.d ./lite/micro/kernels/cumsum.o ./lite/micro/kernels/cumsum.su ./lite/micro/kernels/depth_to_space.cyclo ./lite/micro/kernels/depth_to_space.d ./lite/micro/kernels/depth_to_space.o ./lite/micro/kernels/depth_to_space.su ./lite/micro/kernels/depthwise_conv_common.cyclo ./lite/micro/kernels/depthwise_conv_common.d ./lite/micro/kernels/depthwise_conv_common.o ./lite/micro/kernels/depthwise_conv_common.su ./lite/micro/kernels/dequantize.cyclo ./lite/micro/kernels/dequantize.d ./lite/micro/kernels/dequantize.o ./lite/micro/kernels/dequantize.su ./lite/micro/kernels/dequantize_common.cyclo ./lite/micro/kernels/dequantize_common.d ./lite/micro/kernels/dequantize_common.o ./lite/micro/kernels/dequantize_common.su ./lite/micro/kernels/detection_postprocess.cyclo ./lite/micro/kernels/detection_postprocess.d ./lite/micro/kernels/detection_postprocess.o ./lite/micro/kernels/detection_postprocess.su ./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cyclo ./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d ./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o ./lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.su ./lite/micro/kernels/div.cyclo ./lite/micro/kernels/div.d ./lite/micro/kernels/div.o ./lite/micro/kernels/div.su ./lite/micro/kernels/elementwise.cyclo ./lite/micro/kernels/elementwise.d ./lite/micro/kernels/elementwise.o ./lite/micro/kernels/elementwise.su ./lite/micro/kernels/elu.cyclo ./lite/micro/kernels/elu.d ./lite/micro/kernels/elu.o ./lite/micro/kernels/elu.su ./lite/micro/kernels/ethosu.cyclo ./lite/micro/kernels/ethosu.d ./lite/micro/kernels/ethosu.o ./lite/micro/kernels/ethosu.su ./lite/micro/kernels/exp.cyclo ./lite/micro/kernels/exp.d ./lite/micro/kernels/exp.o ./lite/micro/kernels/exp.su ./lite/micro/kernels/expand_dims.cyclo ./lite/micro/kernels/expand_dims.d ./lite/micro/kernels/expand_dims.o ./lite/micro/kernels/expand_dims.su ./lite/micro/kernels/fill.cyclo ./lite/micro/kernels/fill.d ./lite/micro/kernels/fill.o ./lite/micro/kernels/fill.su ./lite/micro/kernels/floor.cyclo ./lite/micro/kernels/floor.d ./lite/micro/kernels/floor.o ./lite/micro/kernels/floor.su ./lite/micro/kernels/floor_div.cyclo ./lite/micro/kernels/floor_div.d ./lite/micro/kernels/floor_div.o ./lite/micro/kernels/floor_div.su ./lite/micro/kernels/floor_mod.cyclo ./lite/micro/kernels/floor_mod.d ./lite/micro/kernels/floor_mod.o ./lite/micro/kernels/floor_mod.su ./lite/micro/kernels/fully_connected_common.cyclo ./lite/micro/kernels/fully_connected_common.d ./lite/micro/kernels/fully_connected_common.o ./lite/micro/kernels/fully_connected_common.su ./lite/micro/kernels/gather.cyclo ./lite/micro/kernels/gather.d ./lite/micro/kernels/gather.o ./lite/micro/kernels/gather.su ./lite/micro/kernels/gather_nd.cyclo ./lite/micro/kernels/gather_nd.d ./lite/micro/kernels/gather_nd.o ./lite/micro/kernels/gather_nd.su ./lite/micro/kernels/hard_swish.cyclo ./lite/micro/kernels/hard_swish.d ./lite/micro/kernels/hard_swish.o ./lite/micro/kernels/hard_swish.su ./lite/micro/kernels/hard_swish_common.cyclo ./lite/micro/kernels/hard_swish_common.d
	-$(RM) ./lite/micro/kernels/hard_swish_common.o ./lite/micro/kernels/hard_swish_common.su ./lite/micro/kernels/if.cyclo ./lite/micro/kernels/if.d ./lite/micro/kernels/if.o ./lite/micro/kernels/if.su ./lite/micro/kernels/kernel_runner.cyclo ./lite/micro/kernels/kernel_runner.d ./lite/micro/kernels/kernel_runner.o ./lite/micro/kernels/kernel_runner.su ./lite/micro/kernels/kernel_util.cyclo ./lite/micro/kernels/kernel_util.d ./lite/micro/kernels/kernel_util.o ./lite/micro/kernels/kernel_util.su ./lite/micro/kernels/l2_pool_2d.cyclo ./lite/micro/kernels/l2_pool_2d.d ./lite/micro/kernels/l2_pool_2d.o ./lite/micro/kernels/l2_pool_2d.su ./lite/micro/kernels/l2norm.cyclo ./lite/micro/kernels/l2norm.d ./lite/micro/kernels/l2norm.o ./lite/micro/kernels/l2norm.su ./lite/micro/kernels/leaky_relu.cyclo ./lite/micro/kernels/leaky_relu.d ./lite/micro/kernels/leaky_relu.o ./lite/micro/kernels/leaky_relu.su ./lite/micro/kernels/leaky_relu_common.cyclo ./lite/micro/kernels/leaky_relu_common.d ./lite/micro/kernels/leaky_relu_common.o ./lite/micro/kernels/leaky_relu_common.su ./lite/micro/kernels/log_softmax.cyclo ./lite/micro/kernels/log_softmax.d ./lite/micro/kernels/log_softmax.o ./lite/micro/kernels/log_softmax.su ./lite/micro/kernels/logical.cyclo ./lite/micro/kernels/logical.d ./lite/micro/kernels/logical.o ./lite/micro/kernels/logical.su ./lite/micro/kernels/logical_common.cyclo ./lite/micro/kernels/logical_common.d ./lite/micro/kernels/logical_common.o ./lite/micro/kernels/logical_common.su ./lite/micro/kernels/logistic.cyclo ./lite/micro/kernels/logistic.d ./lite/micro/kernels/logistic.o ./lite/micro/kernels/logistic.su ./lite/micro/kernels/logistic_common.cyclo ./lite/micro/kernels/logistic_common.d ./lite/micro/kernels/logistic_common.o ./lite/micro/kernels/logistic_common.su ./lite/micro/kernels/lstm_eval.cyclo ./lite/micro/kernels/lstm_eval.d ./lite/micro/kernels/lstm_eval.o ./lite/micro/kernels/lstm_eval.su ./lite/micro/kernels/maximum_minimum.cyclo ./lite/micro/kernels/maximum_minimum.d ./lite/micro/kernels/maximum_minimum.o ./lite/micro/kernels/maximum_minimum.su ./lite/micro/kernels/micro_tensor_utils.cyclo ./lite/micro/kernels/micro_tensor_utils.d ./lite/micro/kernels/micro_tensor_utils.o ./lite/micro/kernels/micro_tensor_utils.su ./lite/micro/kernels/mirror_pad.cyclo ./lite/micro/kernels/mirror_pad.d ./lite/micro/kernels/mirror_pad.o ./lite/micro/kernels/mirror_pad.su ./lite/micro/kernels/mul_common.cyclo ./lite/micro/kernels/mul_common.d ./lite/micro/kernels/mul_common.o ./lite/micro/kernels/mul_common.su ./lite/micro/kernels/neg.cyclo ./lite/micro/kernels/neg.d ./lite/micro/kernels/neg.o ./lite/micro/kernels/neg.su ./lite/micro/kernels/pack.cyclo ./lite/micro/kernels/pack.d ./lite/micro/kernels/pack.o ./lite/micro/kernels/pack.su ./lite/micro/kernels/pad.cyclo ./lite/micro/kernels/pad.d ./lite/micro/kernels/pad.o ./lite/micro/kernels/pad.su ./lite/micro/kernels/pooling_common.cyclo ./lite/micro/kernels/pooling_common.d ./lite/micro/kernels/pooling_common.o ./lite/micro/kernels/pooling_common.su ./lite/micro/kernels/prelu.cyclo ./lite/micro/kernels/prelu.d ./lite/micro/kernels/prelu.o ./lite/micro/kernels/prelu.su ./lite/micro/kernels/prelu_common.cyclo ./lite/micro/kernels/prelu_common.d ./lite/micro/kernels/prelu_common.o ./lite/micro/kernels/prelu_common.su ./lite/micro/kernels/quantize.cyclo ./lite/micro/kernels/quantize.d ./lite/micro/kernels/quantize.o ./lite/micro/kernels/quantize.su ./lite/micro/kernels/quantize_common.cyclo ./lite/micro/kernels/quantize_common.d ./lite/micro/kernels/quantize_common.o ./lite/micro/kernels/quantize_common.su ./lite/micro/kernels/read_variable.cyclo ./lite/micro/kernels/read_variable.d ./lite/micro/kernels/read_variable.o ./lite/micro/kernels/read_variable.su ./lite/micro/kernels/reduce.cyclo ./lite/micro/kernels/reduce.d ./lite/micro/kernels/reduce.o ./lite/micro/kernels/reduce.su ./lite/micro/kernels/reduce_common.cyclo ./lite/micro/kernels/reduce_common.d ./lite/micro/kernels/reduce_common.o ./lite/micro/kernels/reduce_common.su ./lite/micro/kernels/reshape.cyclo ./lite/micro/kernels/reshape.d ./lite/micro/kernels/reshape.o ./lite/micro/kernels/reshape.su ./lite/micro/kernels/resize_bilinear.cyclo ./lite/micro/kernels/resize_bilinear.d ./lite/micro/kernels/resize_bilinear.o ./lite/micro/kernels/resize_bilinear.su ./lite/micro/kernels/resize_nearest_neighbor.cyclo ./lite/micro/kernels/resize_nearest_neighbor.d ./lite/micro/kernels/resize_nearest_neighbor.o ./lite/micro/kernels/resize_nearest_neighbor.su ./lite/micro/kernels/round.cyclo ./lite/micro/kernels/round.d ./lite/micro/kernels/round.o ./lite/micro/kernels/round.su ./lite/micro/kernels/shape.cyclo ./lite/micro/kernels/shape.d ./lite/micro/kernels/shape.o ./lite/micro/kernels/shape.su ./lite/micro/kernels/slice.cyclo ./lite/micro/kernels/slice.d ./lite/micro/kernels/slice.o ./lite/micro/kernels/slice.su ./lite/micro/kernels/softmax_common.cyclo ./lite/micro/kernels/softmax_common.d ./lite/micro/kernels/softmax_common.o ./lite/micro/kernels/softmax_common.su ./lite/micro/kernels/space_to_batch_nd.cyclo ./lite/micro/kernels/space_to_batch_nd.d ./lite/micro/kernels/space_to_batch_nd.o ./lite/micro/kernels/space_to_batch_nd.su ./lite/micro/kernels/space_to_depth.cyclo ./lite/micro/kernels/space_to_depth.d ./lite/micro/kernels/space_to_depth.o ./lite/micro/kernels/space_to_depth.su ./lite/micro/kernels/split.cyclo ./lite/micro/kernels/split.d ./lite/micro/kernels/split.o ./lite/micro/kernels/split.su ./lite/micro/kernels/split_v.cyclo ./lite/micro/kernels/split_v.d ./lite/micro/kernels/split_v.o ./lite/micro/kernels/split_v.su ./lite/micro/kernels/squared_difference.cyclo ./lite/micro/kernels/squared_difference.d ./lite/micro/kernels/squared_difference.o ./lite/micro/kernels/squared_difference.su ./lite/micro/kernels/squeeze.cyclo ./lite/micro/kernels/squeeze.d ./lite/micro/kernels/squeeze.o ./lite/micro/kernels/squeeze.su ./lite/micro/kernels/strided_slice.cyclo
	-$(RM) ./lite/micro/kernels/strided_slice.d ./lite/micro/kernels/strided_slice.o ./lite/micro/kernels/strided_slice.su ./lite/micro/kernels/sub.cyclo ./lite/micro/kernels/sub.d ./lite/micro/kernels/sub.o ./lite/micro/kernels/sub.su ./lite/micro/kernels/sub_common.cyclo ./lite/micro/kernels/sub_common.d ./lite/micro/kernels/sub_common.o ./lite/micro/kernels/sub_common.su ./lite/micro/kernels/svdf_common.cyclo ./lite/micro/kernels/svdf_common.d ./lite/micro/kernels/svdf_common.o ./lite/micro/kernels/svdf_common.su ./lite/micro/kernels/tanh.cyclo ./lite/micro/kernels/tanh.d ./lite/micro/kernels/tanh.o ./lite/micro/kernels/tanh.su ./lite/micro/kernels/transpose.cyclo ./lite/micro/kernels/transpose.d ./lite/micro/kernels/transpose.o ./lite/micro/kernels/transpose.su ./lite/micro/kernels/transpose_conv.cyclo ./lite/micro/kernels/transpose_conv.d ./lite/micro/kernels/transpose_conv.o ./lite/micro/kernels/transpose_conv.su ./lite/micro/kernels/unidirectional_sequence_lstm.cyclo ./lite/micro/kernels/unidirectional_sequence_lstm.d ./lite/micro/kernels/unidirectional_sequence_lstm.o ./lite/micro/kernels/unidirectional_sequence_lstm.su ./lite/micro/kernels/unpack.cyclo ./lite/micro/kernels/unpack.d ./lite/micro/kernels/unpack.o ./lite/micro/kernels/unpack.su ./lite/micro/kernels/var_handle.cyclo ./lite/micro/kernels/var_handle.d ./lite/micro/kernels/var_handle.o ./lite/micro/kernels/var_handle.su ./lite/micro/kernels/while.cyclo ./lite/micro/kernels/while.d ./lite/micro/kernels/while.o ./lite/micro/kernels/while.su ./lite/micro/kernels/zeros_like.cyclo ./lite/micro/kernels/zeros_like.d ./lite/micro/kernels/zeros_like.o ./lite/micro/kernels/zeros_like.su

.PHONY: clean-lite-2f-micro-2f-kernels

